---
title: "merging CAMA AND DCRA "
author: "jean landry binam keyanfe"
date: "April 10, 2019"
output: word_document
---

```{r , echo= TRUE}
library(tidyverse)
library(lubridate)
```

========================================================================================================================================

LOADING DCRA AND MERGE CAMA DATASET
```{r ,echo=TRUE}
setwd("C:/Users/Landry B. Keyanfe/Desktop/introanalytic/project")
permit=read_csv('permit_reviews_an.csv')
summary(permit)
```

```{r}
setwd("C:/Users/Landry B. Keyanfe/Desktop/introanalytic/project")
cama=read_csv('cama_common.csv')
summary(cama)
```

=====================================================================================================================================

ACESSING MISSING VALUES

```{r,echo=TRUE}
# Function acessing the missing values
permit_missing <- function(df){
  missing <- df %>% 
    mutate_all(is.na) %>% 
    summarise_all(sum) %>% 
    gather(variable, missing)
  return(missing)
}

```


```{r}
#accesing missing values DCRA database
print(permit_missing(permit))
```

```{r}

```

```{r}
#acessing missing values Merged cama database
print(permit_missing(cama))
```
======================================================================================================================================


=========================== MERGING THE TWO DATA BASE (DCRA AND MEREG CAMA)=============================================================

```{r}
#renaming SSL variable
permit$SSL=permit$ssl

#joinning the two datasets
data <- permit %>% 
  left_join(cama, by = "SSL")
```

```{r}
#accesing missing values in the new data set
print(permit_missing(data))
```
======================================================================



```{r}
data2= select(data,SSL,alias, permit_cap_status,pdox_b1_id,use_type,Project_Status,Project_Description,TaskName,TaskStatus,RC_ReviewStatus,RC_HowAssigned,ReviewCycle,elapsed_workdays,Fee_Assessed,job_class,over_30,AGENCY,pdox,est_worktime,Ward,rc_1_time,rc_time,permit_type,proposed_use_of_building,proposed_number_stories,proposed_number_units,existing_number_units,green_floor_area,OBJECTID, SALEDATE, PRICE, QUALIFIED, AYB, EYB, SALE_NUM,
       LIVING_GBA, USECODE, LANDAREA, GIS_LAST_MOD_DTTM)
```

w
```{r}
#Creating dataframe containing rows with missing values

na_vec2=which(!complete.cases(data2))
  
data2=data2[-na_vec2,]



```

```{r}
#filtering by permit issued
data3=filter(data2,permit_cap_status=='Permit Issued')
```

```{r}
data3%>%
  group_by(TaskName)%>%
  summarise(count=n())%>%
  arrange(desc(count))

```

```{r}
data3%>%
  group_by(AGENCY)%>%
  summarise(count=n())%>%
  arrange(desc(count))
```

