---
title: "PLOT"
author: "jean landry binam keyanfe"
date: "April 14, 2019"
output: word_document
---
```{r}
library(tidyverse)
data <- read_csv(file = 'cleaned_merged_data5.csv', col_names = TRUE)
```

```{r,fig.align="center",fig.width=7,fig.height=4}
#plot the number of application per gency involve 
data %>%
  filter(data$permit_cap_status=="Permit Issued")%>%
  ggplot(aes(GroupName)) + coord_flip()+
  geom_bar()
  
  
  
```

```{r}
#plot permit issued per ward
data %>% 
  filter(data$permit_cap_status=="Permit Issued")%>%
  ggplot(aes(Ward))+geom_bar(fill='041e42')+labs(x='Ward Number',y= "Number of Permit Issued", title="Permit Issued per Ward")

  
  
```

```{r}
#plot permit applicationper review cycle
require(scales)
data$ReviewCycle2=ifelse(data$ReviewCycle>=5,"5+",data$ReviewCycle)
data %>% 
  filter(permit_cap_status =="Permit Issued")%>%
  ggplot(aes(x = factor(ReviewCycle2))) +  geom_bar(aes(y = (..count..)/sum(..count..)), fill='blue') +scale_y_continuous(labels=percent)+labs(x='Number of Review Cycle',y= "Number of Applications", title="Permit Applications per Number of Review Cycle")



```


```{r}
#create a ttime vatiable categorizing elapsed days
data$time=ifelse(data$elapsed_workdays<=30,'<30',ifelse(data$elapsed_workdays>30 & data$elapsed_workdays<= 60,'<60',ifelse(data$elapsed_workdays>60 & data$elapsed_workdays<= 90,'<90','>90') ))
data%>%
  group_by(time,)%>%
  summarise(count=n())%>%
 
  arrange(desc(count))
```

```{r}
#plot permit issues per elapsed days
data %>% 
  filter(permit_cap_status =="Permit Issued")%>%
  ggplot(aes(x = factor(time))) +  geom_bar(aes(y = (..count..)/sum(..count..)), fill='red') +scale_y_continuous(labels=percent)+labs(x='Number of Elapsed Days',y= "Number of Permit Issued", title="Permit Issued per Elapsed Days")

```


```{r}
#plot 
data %>% 
  filter(data$permit_cap_status=="Permit Issued")%>%
  ggplot(aes(factor(ReviewCycle),elapsed_workdays))+geom_point(color='blue') +labs(x='Number of Review Cycles',y= "Elapse Workdays",    title="Elapsed Workdays grouped by review cycle")

  


```





